#!/bin/bash

echo "🌐 ACCESS URLS FOR GST RECONCILIATION SYSTEM"
echo "============================================"
echo ""
echo "🔧 DEVELOPMENT TOOLS:"
echo "  1. Backend API:          http://localhost:3000"
echo "  2. Traefik Dashboard:    http://localhost:8085"
echo "  3. Adminer (Database):   http://localhost:8082"
echo ""
echo "🗄️  STORAGE & QUEUES:"
echo "  4. MinIO Console:        http://localhost:9091"
echo "     Username: minioadmin"
echo "     Password: MinioAdmin123"
echo ""
echo "  5. RabbitMQ Management:  http://localhost:15673"
echo "     Username: rabbitadmin"
echo "     Password: RabbitAdmin123"
echo ""
echo "  6. NATS Monitoring:      http://localhost:8222"
echo ""
echo "📧 EMAIL TESTING:"
echo "  7. MailHog Web UI:       http://localhost:8025"
echo ""
echo "🔐 AUTHENTICATION:"
echo "  8. Keycloak Admin:       http://localhost:8080"
echo "     Username: admin"
echo "     Password: Admin123"
echo ""
echo "🚪 API GATEWAY:"
echo "  9. Kong Admin API:       http://localhost:8003"
echo " 10. Kong Proxy:           http://localhost:8002"
echo ""
echo "📊 DATABASE CONNECTIONS:"
echo "  PostgreSQL Main:         localhost:5432"
echo "    Database: gst_recon"
echo "    Username: gstadmin"
echo "    Password: GstAdmin123"
echo ""
echo "  PostgreSQL Keycloak:     localhost:5433"
echo "    Database: keycloak"
echo "    Username: keycloak"
echo "    Password: Keycloak123"
echo ""
echo "  PostgreSQL Kong:         localhost:5434"
echo "    Database: kong"
echo "    Username: kong"
echo "    Password: Kong123"
echo ""
echo "🧪 QUICK TESTS:"
echo "  curl http://localhost:3000/api/health"
echo "  curl http://localhost:3000/api/tenants"
echo "  curl -X POST http://localhost:3000/api/upload-test"
echo ""
echo "============================================"
