BEGIN;

CREATE TABLE IF NOT EXISTS sales_invoices (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    tax_period_id UUID REFERENCES tax_periods(id),
    invoice_type VARCHAR(20) NOT NULL CHECK (invoice_type IN ('B2B','B2C_SMALL','B2C_LARGE','EXPORT','SEZ','DEBIT_NOTE','CREDIT_NOTE')),
    original_invoice_id UUID REFERENCES sales_invoices(id) ON DELETE SET NULL,
    is_amendment BOOLEAN DEFAULT FALSE,
    amendment_reason TEXT,
    filing_status VARCHAR(20) DEFAULT 'NOT_FILED' CHECK (filing_status IN ('NOT_FILED', 'READY', 'FILED', 'FAILED')),
    filing_date DATE,
    filing_period CHAR(6),
    invoice_number VARCHAR(100) NOT NULL,
    invoice_date DATE NOT NULL,
    due_date DATE,
    book_type VARCHAR(2) NOT NULL CHECK (book_type IN ('SA','SR','CN','DN')),
    entry_serial_no INTEGER DEFAULT 0,
    customer_id UUID REFERENCES supplier_master(id),
    customer_name VARCHAR(500),
    customer_gstin CHAR(15),
    place_of_supply VARCHAR(100),
    is_interstate BOOLEAN DEFAULT FALSE,
    reverse_charge BOOLEAN DEFAULT FALSE,
    total_taxable_value NUMERIC(15, 2) DEFAULT 0,
    total_igst NUMERIC(15, 2) DEFAULT 0,
    total_cgst NUMERIC(15, 2) DEFAULT 0,
    total_sgst NUMERIC(15, 2) DEFAULT 0,
    total_cess NUMERIC(15, 2) DEFAULT 0,
    total_invoice_value NUMERIC(15, 2) DEFAULT 0,
    round_off NUMERIC(8, 2) DEFAULT 0,
    payment_status VARCHAR(20) DEFAULT 'UNPAID' CHECK (payment_status IN ('UNPAID','PARTIAL','PAID','OVERDUE')),
    amount_paid NUMERIC(15,2) DEFAULT 0,
    created_by UUID REFERENCES users(id),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_sales_invoice_unique UNIQUE (tenant_id, workspace_id, book_type, invoice_number, tax_period_id)
);

CREATE TABLE IF NOT EXISTS sales_invoice_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    invoice_id UUID NOT NULL REFERENCES sales_invoices(id) ON DELETE CASCADE,
    line_number INTEGER NOT NULL,
    hsn_sac_code VARCHAR(10),
    description TEXT,
    quantity NUMERIC(15, 3) DEFAULT 0,
    uom VARCHAR(20),
    unit_rate NUMERIC(15, 4) DEFAULT 0,
    taxable_value NUMERIC(15, 2) NOT NULL,
    gst_rate_percent NUMERIC(5, 2),
    igst_amount NUMERIC(15, 2) DEFAULT 0,
    cgst_amount NUMERIC(15, 2) DEFAULT 0,
    sgst_amount NUMERIC(15, 2) DEFAULT 0,
    cess_amount NUMERIC(15, 2) DEFAULT 0,
    total_amount_with_tax NUMERIC(15, 2) DEFAULT 0,
    is_rcm BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS expense_vouchers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    workspace_id UUID NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
    tax_period_id UUID REFERENCES tax_periods(id),
    voucher_type VARCHAR(20) CHECK (voucher_type IN ('PURCHASE','EXPENSE','DEBIT_NOTE','CREDIT_NOTE')),
    parent_voucher_id UUID REFERENCES expense_vouchers(id) ON DELETE SET NULL,
    filing_status VARCHAR(20) DEFAULT 'NOT_FILED',
    filing_date DATE,
    filing_period CHAR(6),
    supplier_id UUID REFERENCES supplier_master(id),
    supplier_name VARCHAR(500),
    supplier_gstin CHAR(15),
    supplier_invoice_no VARCHAR(100) NOT NULL,
    supplier_invoice_date DATE,
    due_date DATE,
    taxable_total NUMERIC(15, 2) DEFAULT 0,
    net_amount NUMERIC(15, 2) NOT NULL,
    total_cgst_amount NUMERIC(15, 2) DEFAULT 0,
    total_sgst_amount NUMERIC(15, 2) DEFAULT 0,
    total_igst_amount NUMERIC(15, 2) DEFAULT 0,
    total_cess_amount NUMERIC(15, 2) DEFAULT 0,
    itc_eligible BOOLEAN DEFAULT TRUE,
    itc_claimed BOOLEAN DEFAULT FALSE,
    itc_claimed_period CHAR(6),
    payment_status VARCHAR(20) DEFAULT 'UNPAID' CHECK (payment_status IN ('UNPAID','PARTIAL','PAID','OVERDUE')),
    amount_paid NUMERIC(15,2) DEFAULT 0,
    created_by UUID REFERENCES users(id),
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS expense_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v7(),
    expense_id UUID NOT NULL REFERENCES expense_vouchers(id) ON DELETE CASCADE,
    account_id UUID,
    hsn_code VARCHAR(10),
    description TEXT,
    quantity NUMERIC(15, 3) DEFAULT 0,
    uom VARCHAR(20),
    unit_rate NUMERIC(15, 4) DEFAULT 0,
    gross_amount NUMERIC(15, 2) DEFAULT 0,
    discount_amount NUMERIC(15, 2) DEFAULT 0,
    taxable_amount NUMERIC(15, 2) DEFAULT 0,
    tax_per NUMERIC(5, 2),
    igst_amount NUMERIC(15, 2) DEFAULT 0,
    cgst_amount NUMERIC(15, 2) DEFAULT 0,
    sgst_amount NUMERIC(15, 2) DEFAULT 0,
    cess_amount NUMERIC(15, 2) DEFAULT 0,
    total_amount_with_tax NUMERIC(15, 2) DEFAULT 0,
    is_rcm BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

COMMIT;
