-- Create GSTR-2A specific tables
CREATE TABLE IF NOT EXISTS public.gstr_2a_b2b_invoices (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    workspace_id UUID NOT NULL,
    filing_id UUID NOT NULL,
    supplier_gstin VARCHAR(15),
    supplier_name VARCHAR(255),
    invoice_number VARCHAR(100),
    invoice_date DATE,
    invoice_value NUMERIC(15,2),
    place_of_supply VARCHAR(100),
    reverse_charge VARCHAR(10),
    invoice_type VARCHAR(50),
    rate NUMERIC(5,2),
    taxable_value NUMERIC(15,2),
    integrated_tax NUMERIC(15,2),
    central_tax NUMERIC(15,2),
    state_tax NUMERIC(15,2),
    cess NUMERIC(15,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.gstr_2a_cdnr (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    workspace_id UUID NOT NULL,
    filing_id UUID NOT NULL,
    supplier_gstin VARCHAR(15),
    supplier_name VARCHAR(255),
    note_number VARCHAR(100),
    note_date DATE,
    note_type VARCHAR(10),
    place_of_supply VARCHAR(100),
    reverse_charge VARCHAR(10),
    note_value NUMERIC(15,2),
    rate NUMERIC(5,2),
    taxable_value NUMERIC(15,2),
    integrated_tax NUMERIC(15,2),
    central_tax NUMERIC(15,2),
    state_tax NUMERIC(15,2),
    cess NUMERIC(15,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.gstr_2a_b2ba_invoices (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    workspace_id UUID NOT NULL,
    filing_id UUID NOT NULL,
    supplier_gstin VARCHAR(15),
    supplier_name VARCHAR(255),
    original_invoice_number VARCHAR(100),
    original_invoice_date DATE,
    revised_invoice_number VARCHAR(100),
    revised_invoice_date DATE,
    invoice_value NUMERIC(15,2),
    place_of_supply VARCHAR(100),
    reverse_charge VARCHAR(10),
    invoice_type VARCHAR(50),
    rate NUMERIC(5,2),
    taxable_value NUMERIC(15,2),
    integrated_tax NUMERIC(15,2),
    central_tax NUMERIC(15,2),
    state_tax NUMERIC(15,2),
    cess NUMERIC(15,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.gstr_2a_cdnra (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    workspace_id UUID NOT NULL,
    filing_id UUID NOT NULL,
    supplier_gstin VARCHAR(15),
    supplier_name VARCHAR(255),
    original_note_number VARCHAR(100),
    original_note_date DATE,
    revised_note_number VARCHAR(100),
    revised_note_date DATE,
    note_type VARCHAR(10),
    place_of_supply VARCHAR(100),
    reverse_charge VARCHAR(10),
    note_value NUMERIC(15,2),
    rate NUMERIC(5,2),
    taxable_value NUMERIC(15,2),
    integrated_tax NUMERIC(15,2),
    central_tax NUMERIC(15,2),
    state_tax NUMERIC(15,2),
    cess NUMERIC(15,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.gstr_2a_isd (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    workspace_id UUID NOT NULL,
    filing_id UUID NOT NULL,
    isd_gstin VARCHAR(15),
    isd_name VARCHAR(255),
    document_number VARCHAR(100),
    document_date DATE,
    document_type VARCHAR(50),
    itc_integrated_tax NUMERIC(15,2),
    itc_central_tax NUMERIC(15,2),
    itc_state_tax NUMERIC(15,2),
    itc_cess NUMERIC(15,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.gstr_2a_impg (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    workspace_id UUID NOT NULL,
    filing_id UUID NOT NULL,
    port_code VARCHAR(10),
    boe_number VARCHAR(50),
    boe_date DATE,
    boe_value NUMERIC(15,2),
    document_type VARCHAR(50),
    rate NUMERIC(5,2),
    taxable_value NUMERIC(15,2),
    integrated_tax NUMERIC(15,2),
    cess NUMERIC(15,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
