const fs = require('fs');
const xlsx = require('xlsx');

const filePath = '/home/tanvir/Desktop/gsttool_project/GSTR2B./a1b_purchase_book_data_fy2017_fy2025-26.csv';
const workbook = xlsx.readFile(filePath);
const sheetName = workbook.SheetNames[0];
const jsonRows = xlsx.utils.sheet_to_json(workbook.Sheets[sheetName], { header: 1 });

console.log("Total rows from xlsx library:", jsonRows.length);

const { processPurchaseSheet } = require('./src/utils/bookSheetProcessors');

// Dummy IDs
const tenantId = '11111111-1111-1111-1111-111111111111';
const workspaceId = '22222222-2222-2222-2222-222222222222';
const taxPeriodId = '33333333-3333-3333-3333-333333333333';

const vouchers = processPurchaseSheet(jsonRows, tenantId, workspaceId, taxPeriodId, '052026', '27ABCDE1234F1Z5', 'PURCHASE');
console.log("Vouchers generated by processPurchaseSheet:", vouchers.length);

// Analyze conflict keys if we use a single taxPeriodId for the whole file
const conflictKeys = new Map();
let conflicts = 0;

vouchers.forEach(v => {
    const key = `${v.header.book_type}__${v.header.supplier_invoice_no}`;
    if (conflictKeys.has(key)) {
        conflicts++;
        conflictKeys.get(key).push(v.header.supplier_invoice_date);
    } else {
        conflictKeys.set(key, [v.header.supplier_invoice_date]);
    }
});

console.log(`Unique Invoice Numbers (Conflict Keys): ${conflictKeys.size}`);
console.log(`Theoretical overwrites if using a single Tax Period: ${conflicts}`);
console.log(`Unique records that would actually stick in DB: ${conflictKeys.size}`);

// Sample some conflicts to see if they are actually different dates
console.log("\nSample Conflicts (Same Inv No, Different Dates):");
let samples = 0;
for (const [key, dates] of conflictKeys.entries()) {
    if (dates.length > 1 && samples < 5) {
        console.log(`Inv: ${key} -> Dates: ${dates.join(', ')}`);
        samples++;
    }
}

// Check how many unique (book_type, supplier_invoice_no, YEAR_MONTH) combinations there are
const monthlyKeys = new Set();
vouchers.forEach(v => {
    const month = v.header.supplier_invoice_date.substring(0, 7);
    const key = `${v.header.book_type}__${v.header.supplier_invoice_no}__${month}`;
    monthlyKeys.add(key);
});

console.log(`\nUnique records if each row was assigned its ACTUAL tax period: ${monthlyKeys.size}`);
